apiVersion: v1
kind: PersistentVolume
metadata:
  name: h2-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 'F:\TUA\code-with-quarkus\Docker\data'

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: h2-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: h2-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: h2-database
  template:
    metadata:
      labels:
        app: h2-database
    spec:
      containers:
        - name: h2-database
          image: oscarfonts/h2
          env:
            - name: H2_USER
              value: admin
            - name: H2_PASSWORD
              value: admin
          ports:
            - containerPort: 1521
          volumeMounts:
            - name: h2-data
              mountPath: /opt/h2-data
      volumes:
        - name: h2-data
          persistentVolumeClaim:
            claimName: h2-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: h2-database-service
spec:
  selector:
    app: h2-database
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521