apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 52d66e63f4bd2fd6b2089a50c1b69aa958e488e3
    app.quarkus.io/build-timestamp: "2023-12-03 - 14:49:51 +0000"
  labels:
    app.kubernetes.io/name: ssbd01
    app.kubernetes.io/version: 0.0.1
  name: ssbd01
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: ssbd01
    app.kubernetes.io/version: 0.0.1
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 52d66e63f4bd2fd6b2089a50c1b69aa958e488e3
    app.quarkus.io/build-timestamp: "2023-12-03 - 14:49:51 +0000"
  labels:
    app.kubernetes.io/name: ssbd01
    app.kubernetes.io/version: 0.0.1
  name: ssbd01
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ssbd01
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 52d66e63f4bd2fd6b2089a50c1b69aa958e488e3
        app.quarkus.io/build-timestamp: "2023-12-03 - 14:49:51 +0000"
      labels:
        app.kubernetes.io/name: ssbd01
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: wiktor/ssbd01:0.0.1
          imagePullPolicy: IfNotPresent
          name: ssbd01
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
